--DROP TABLE FoodData;

CREATE TABLE FoodData (
-- FoodId			INT			PRIMARY KEY IDENTITY ,
DatabaseNumber		INTEGER PRIMARY KEY AUTOINCREMENT,
FoodGroup 			VARCHAR(100) DEFAULT(NULL) ,
FoodName 			VARCHAR(100) DEFAULT(NULL) ,
ProteinFat  		VARCHAR(100) DEFAULT(NULL) ,
Carbohydrates 		VARCHAR(100) DEFAULT(NULL) ,
Ash 				VARCHAR(100) DEFAULT(NULL) ,
Calories 			VARCHAR(100) DEFAULT(NULL) ,
Starch 			VARCHAR(100) DEFAULT(NULL) ,
Sucrose 			VARCHAR(100) DEFAULT(NULL) ,
Glucose 			VARCHAR(100) DEFAULT(NULL) ,
Fructose 			VARCHAR(100) DEFAULT(NULL) ,
Lactose 			VARCHAR(100) DEFAULT(NULL) ,
Maltose 			VARCHAR(100) DEFAULT(NULL) ,
Alcohol 			VARCHAR(100) DEFAULT(NULL) ,
Water 			VARCHAR(100) DEFAULT(NULL) ,
Caffeine 			VARCHAR(100) DEFAULT(NULL) ,
Theobromine 		VARCHAR(100) DEFAULT(NULL) ,
Sugar 			VARCHAR(100) DEFAULT(NULL) ,
Galactose 			VARCHAR(100) DEFAULT(NULL) ,
Fiber 			VARCHAR(100) DEFAULT(NULL) ,
Calcium 			VARCHAR(100) DEFAULT(NULL) ,
Iron 				VARCHAR(100) DEFAULT(NULL) ,
Magnesium 			VARCHAR(100) DEFAULT(NULL) ,
Phosphorus 			VARCHAR(100) DEFAULT(NULL) ,
Potasssium 			VARCHAR(100) DEFAULT(NULL) ,
Sodium 			VARCHAR(100) DEFAULT(NULL) ,
Zinc 				VARCHAR(100) DEFAULT(NULL) ,
Cupper 			VARCHAR(100) DEFAULT(NULL) ,
Fluoride 			VARCHAR(100) DEFAULT(NULL) ,
Manganese 			VARCHAR(100) DEFAULT(NULL) ,
Selenium 			VARCHAR(100) DEFAULT(NULL) ,
Vitamin 			VARCHAR(100) DEFAULT(NULL) ,
Retinol 			VARCHAR(100) DEFAULT(NULL) ,
RetinolEquivalents 	VARCHAR(100) DEFAULT(NULL) ,
BetaCarotene 		VARCHAR(100) DEFAULT(NULL) ,
AlphaCarotene 		VARCHAR(100) DEFAULT(NULL) ,
VitaminE 			VARCHAR(100) DEFAULT(NULL) ,
VitaminD 			VARCHAR(100) DEFAULT(NULL) ,
VitaminD2 			VARCHAR(100) DEFAULT(NULL) ,
VitaminD3 			VARCHAR(100) DEFAULT(NULL) ,
BetaCryptoxanthin 	VARCHAR(100) DEFAULT(NULL) ,
Lycopene 			VARCHAR(100) DEFAULT(NULL) ,
LuteinAndZeaxanthin 	VARCHAR(100) DEFAULT(NULL) ,
VitaminC 			VARCHAR(100) DEFAULT(NULL) ,
ThiaminB1 			VARCHAR(100) DEFAULT(NULL) ,
RiboflavinB2 		VARCHAR(100) DEFAULT(NULL) ,
NiacinB3 			VARCHAR(100) DEFAULT(NULL) ,
VitaminB5 			VARCHAR(100) DEFAULT(NULL) ,
VitaminB6 			VARCHAR(100) DEFAULT(NULL) ,
FolateB9 			VARCHAR(100) DEFAULT(NULL) ,
VitaminB12 			VARCHAR(100) DEFAULT(NULL) ,
Choline 			VARCHAR(100) DEFAULT(NULL) ,
Cholesterol 		VARCHAR(100) DEFAULT(NULL) ,
SaturatedFat 		VARCHAR(100) DEFAULT(NULL) ,
NetCarbs			VARCHAR(100) DEFAULT(NULL)
);


--SELECT * FROM dbo.FoodData


BULK INSERT dbo.FoodData
FROM './FoodData.txt'
WITH (
	FIRSTROW = 2,
	FIELDTERMINATOR = '\t',
	ROWTERMINATOR = '\n',
	KEEPNULLS
);

--SELECT * FROM dbo.FoodData
